force-app/main/default/objects/Logger__e/Logger__e.object-meta.xml
<CustomObject>
    <description>Logger platform event</description>
    <label>Logger</label>
    <pluralLabel>Logger</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logger__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>Logging Level</description>
    <label>Log Level</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Logged_By__c.field-meta.xml
<CustomField>
    <fullName>Logged_By__c</fullName>
    <description>Logging user</description>
    <label>Logged By</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Main Log message</description>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Class/Process name</description>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Operational source record Id</description>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Full stack trace for detailed debugging</description>
    <label>Stack Trace</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger_Settings__c/Logger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Logger framework</description>
    <label>Logger Settings</label>
</CustomObject>

force-app/main/default/objects/Logger_Settings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Logging enabled?</description>
    <inlineHelpText>Logging enabled?</inlineHelpText>
    <label>Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Settings__c/fields/Errors_Warnings_Only__c.field-meta.xml
<CustomField>
    <fullName>Errors_Warnings_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether by default only errors and warnings are logged</description>
    <inlineHelpText>Whether by default only errors and warnings are logged</inlineHelpText>
    <label>Errors/Warnings Only?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public class Logger {
    
    public enum LogLevel { DEBUG, INFO, WARN, ERROR }
    public static final Logger_Settings__c SETTINGS = Logger_Settings__c.getInstance();
    
    private static List<LogEntry> bufferEntries = new List<LogEntry>();

    public class LogEntry {
        public String message;
        public LogLevel level;
        public String source;
        public String sourceRecordId;
        public String stackTrace;
        
        public LogEntry(String message, LogLevel level, String source, String sourceRecordId, String stackTrace) {
            this.message = message;
            this.level = level == null?LogLevel.INFO:level;
            this.source = source;
            this.sourceRecordId = sourceRecordId;
            this.stackTrace = stackTrace;
        }
    }

    private static Boolean isEnabled() {
        return SETTINGS.Enabled__c;
    }

    private static Boolean allowLogLevel(LogLevel level) {
        if (SETTINGS.Errors_Warnings_Only__c && (level != LogLevel.ERROR && level != LogLevel.WARN))
            return false;
        return true;
    }

    public static void add(String source, String sourceRecordId, String message, LogLevel level) {
        if (!isEnabled() || !allowLogLevel(level)) return;
        bufferEntries.add(new LogEntry(message, level, source, sourceRecordId, null));
    }

    public static void add(String source, String sourceRecordId, Exception e) {
        if (!isEnabled()) return;
        bufferEntries.add(new LogEntry(e.getMessage(), LogLevel.ERROR, source, sourceRecordId, e.getStackTraceString()));
    }

    public static void publish() {
        if (!isEnabled() || bufferEntries.isEmpty()) return;

        List<Logger__e> events = new List<Logger__e>();

        for (LogEntry entry : bufferEntries) {
            if (!allowLogLevel(entry.level)) continue;
            events.add(new Logger__e(
                Logged_By__c = UserInfo.getUserId(),
                Log_Level__c = entry.level.name(),
                Source__c = entry.source,
                Source_Record_Id__c = entry.sourceRecordId,
                Message__c = entry.message,
                Stack_Trace__c = entry.stackTrace
            ));
        }

        if (!events.isEmpty()) {
            Database.SaveResult[] results = EventBus.publish(events);
        }

        bufferEntries.clear();
    }
}