force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object part of the logger framework that stores the information.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>Logging Level</description>
    <inlineHelpText>Logging Level</inlineHelpText>
    <label>Log Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
                <color>#00CCCC</color>
                <label>Debug</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <color>#33CC00</color>
                <label>Info</label>
            </value>
            <value>
                <fullName>WARN</fullName>
                <color>#FFCC33</color>
                <label>Warning</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <color>#FF0000</color>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log message</description>
    <inlineHelpText>Log message</inlineHelpText>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Class/Process name</description>
    <inlineHelpText>Class/Process name</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>Source Object API Name</description>
    <inlineHelpText>Source Object API Name</inlineHelpText>
    <label>Source Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Operational Record Id of the Source Object</description>
    <inlineHelpText>Operational Record Id of the Source Object</inlineHelpText>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Full stack trace for detailed debugging</description>
    <inlineHelpText>Full stack trace for detailed debugging</inlineHelpText>
    <label>Stack Trace</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger__e/Logger__e.object-meta.xml
<CustomObject>
    <description>Logger platform event</description>
    <label>Logger</label>
    <pluralLabel>Logger</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logger__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>Logging Level</description>
    <label>Log Level</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Logged_By__c.field-meta.xml
<CustomField>
    <fullName>Logged_By__c</fullName>
    <description>Logging user</description>
    <label>Logged By</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Main Log message</description>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Class/Process name</description>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Operational source record Id</description>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Full stack trace for detailed debugging</description>
    <label>Stack Trace</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LoggerEventTriggerHandler.cls
public class LoggerEventTriggerHandler extends TriggerHandler {
    /***************************************
     * Private instance variables
    ***************************************/
    private Map<Id, Logger__e> triggerOldMap;
    
    /***************************************
     * Constructors
    ***************************************/
    public LoggerEventTriggerHandler() {
        this.triggerOldMap = (Map<Id, Logger__e>) Trigger.oldMap;
    }
	
    /***************************************
     * Public instance methods
    ***************************************/
    public override void afterInsert() {
        
        List<Log__c> logs = new List<Log__c>();
        for(Logger__e event: (List<Logger__e>)Trigger.New) {
            
            logs.add(new Log__c(
                Source__c = event.Source__c,
                OwnerId = event.Logged_By__c,
                Log_Level__c = event.Log_Level__c,
                Source_Object__c = getSourceObjectName(event.Source_Record_Id__c),
                Source_Record_Id__c = event.Source_Record_Id__c,
                Message__c = event.Message__c,
                Stack_Trace__c = event.Stack_Trace__c
            ));            
        }
        
        if (!logs.isEmpty()) {
            Database.SaveResult[] results = Database.insert(logs, false); // avoids blocking transaction if some logs fail
            for (Integer i = 0; i < results.size(); i++) {
                if (!results[i].isSuccess()) {
                    System.debug('Failed to insert log: ' + results[i].getErrors()[0].getMessage());
                }
            }
        }
    }
    
    /***************************************
     * Private static methods
    ***************************************/
    private static Boolean isId(String idStr) {
        
        if (String.isBlank(idStr)) return false;
        try {
            Id idVal = Id.valueOf(idStr);
            return true;
        } catch (Exception e) {
            return false;
        }        
    }
    
    private static String getSourceObjectName(String recordId) {
        
        if (!isId(recordId)) return ''; 
        Schema.SObjectType objType = ((Id)recordId).getSObjectType(); // Get the sObject type
		return objType.getDescribe().getName();        
    }
}